"""empty message

Revision ID: 1ec8e0701b5a
Revises: d6f9dc8f7807
Create Date: 2024-12-15 19:46:38.954661

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ec8e0701b5a'
down_revision = 'd6f9dc8f7807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_review', schema=None) as batch_op:
        batch_op.drop_column('meLoInvento')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meLoInvento', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
