"""empty message

Revision ID: 2544448be77b
Revises: 79f93c63342c
Create Date: 2024-11-12 15:47:22.686862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2544448be77b'
down_revision = '79f93c63342c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.alter_column('num_features',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('num_products',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.alter_column('num_products',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('num_features',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
