"""empty message

Revision ID: 35c26b7bef5b
Revises: 6f08902b6fce
Create Date: 2024-12-15 16:30:39.857296

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35c26b7bef5b'
down_revision = '6f08902b6fce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('review_score')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.add_column(sa.Column('review_score', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
