"""empty message

Revision ID: d6f9dc8f7807
Revises: 35c26b7bef5b
Create Date: 2024-12-15 17:23:35.401035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6f9dc8f7807'
down_revision = '35c26b7bef5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meLoInvento', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset_review', schema=None) as batch_op:
        batch_op.drop_column('meLoInvento')

    # ### end Alembic commands ###
