# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestVisualizeuvl():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_visualizeuvl(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(1050, 715)
    self.driver.find_element(By.LINK_TEXT, "Sample dataset 4").click()
    self.driver.find_element(By.ID, "btnGroupDropExport10").click()
    self.driver.find_element(By.LINK_TEXT, "Glencoe").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-close").click()
    self.driver.find_element(By.ID, "btnGroupDropExport11").click()
    self.driver.find_element(By.LINK_TEXT, "DIMACS").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-close").click()
    self.driver.find_element(By.ID, "btnGroupDropExport12").click()
    self.driver.find_element(By.LINK_TEXT, "SPLOT").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-close").click()
  
